USE [Optica Industrial]
GO

/****** Object:  Table [dbo].[COMPRA]    Script Date: 16/04/2018 01:57:39 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMPRA](
	[Id Compra] [int] NOT NULL,
	[Id Examen] [int] NULL,
	[Id Producto] [int] NULL,
	[Fecha de Compra] [varchar](50) NULL,
	[Total] [money] NULL,
 CONSTRAINT [PK_COMPRA] PRIMARY KEY CLUSTERED 
(
	[Id Compra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_EXAMEN] FOREIGN KEY([Id Examen])
REFERENCES [dbo].[EXAMEN] ([Id Examen])
GO

ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [FK_COMPRA_EXAMEN]
GO

ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_PRODUCTO] FOREIGN KEY([Id Producto])
REFERENCES [dbo].[PRODUCTO] ([Id Producto])
GO

ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [FK_COMPRA_PRODUCTO]
GO


